### ISSUE TITLE
Newsletter Validation placement in Footer

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#12]
The validation should come below the input field.
![image](https://user-images.githubusercontent.com/97726944/171158265-0d35ddd9-1227-47de-98f6-4b0f9ebff803.png)

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by Shoaibans** [comment]
@ui-chandrashekhar newsletter thank you message color should be different with green tick mark at the left side. (It will look good)
![image](https://user-images.githubusercontent.com/97726944/171350142-eb2323c5-777f-4147-ba84-159fc025971d.png)

**Comment by Shoaibans** [comment]
@ui-chandrashekhar Now the message is not coming properly aligned
![image](https://user-images.githubusercontent.com/97726944/171557690-701e470b-60c3-4a33-ac7f-819d6116cc4e.png)

**Comment by ui-chandrashekhar** [comment]
@Shoaibans REsolved
