### ISSUE TITLE
Different heading font & size in privacy page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#13]
Privacy policy page headings are having different fonts & size.
![image](https://user-images.githubusercontent.com/97726944/171158711-a131e220-4134-4b9f-a682-667c86a37e89.png)
![image](https://user-images.githubusercontent.com/97726944/171158949-f524004f-713d-4fe5-91af-1b8d8539124f.png)

**Comment by Shoaibans** [comment]
@ui-chandrashekhar only above heading is fixed pls check on the whole page.
Video: https://www.awesomescreenshot.com/video/9211084?key=60bafd387a8f3308743cf3aeb7220ec0

**Comment by ui-chandrashekhar** [comment]
@Shoaibans it's content part we can't fix it with code 
@devAlokTripathi @Shweta-PC please look in this issues

**Comment by devAbhishekYadav** [comment]
resolved
