### ISSUE TITLE
Missing contact details from contact page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#15]
![image](https://user-images.githubusercontent.com/97726944/171159503-34788a67-677e-4bfc-a4b7-649cb1e6e875.png)

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/171510677-73ac2336-3f5f-4e25-ba01-68339b201cbd.png)
resolved
