### ISSUE TITLE
Missing validation from contact form

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#16]
The validation is missing from contact form.
![image](https://user-images.githubusercontent.com/97726944/171159642-1210ea62-a97f-48da-b13a-2e3e9e218c92.png)

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/171509682-6af9dc1a-bc0b-47a6-8776-631c26a3132d.png)
resolved
