### ISSUE TITLE
Fashion sunglasses name in link

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#17]
The link is showing Women's fashion sunglasses, but in nav bar & collection it is showing only fashion sunglasses.
https://k4yevf5hpl14tk20-52441481398.shopifypreview.com/collections/women-s-fashion-sunglasses
![image](https://user-images.githubusercontent.com/97726944/171160060-ce00318b-8e20-4908-b8c0-3cd3d059468a.png)

**Comment by devAbhishekYadav** [comment]
resolved
