### ISSUE TITLE
Link name in Cycling sunglasses

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#18]
The title in nav bar & collection page is only Cycling sunglasses but in link it is showing as Men's cycling sunglasses
![image](https://user-images.githubusercontent.com/97726944/171160446-91b688c3-9a41-487a-a291-a9c7b685d0a9.png)

**Comment by devAbhishekYadav** [comment]
resolved

**Comment by devAbhishekYadav** [comment]
resolved
