### ISSUE TITLE
Link name in ski sunglasses & ski masks page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#19]
The link is showing Men's ski sunglasses but in nav bar & collection page it is Ski sunglasses & ski masks
![image](https://user-images.githubusercontent.com/97726944/171160845-6b36caa4-1538-4667-9461-85dd6e86c477.png)

**Comment by devAbhishekYadav** [comment]
resolved
