### ISSUE TITLE
Homepage Banners linking

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#2]
1: The banner is of wooden sunglasses but linked with driving sunglasses page.
![image](https://user-images.githubusercontent.com/97726944/171149491-cdde736a-211d-4649-8ea5-e674f22d311e.png)
2: The banner is of Steampunk & foldable sunglasses but linked with women fashion sunglasses page.
![image](https://user-images.githubusercontent.com/97726944/171149734-ce0734fd-308f-44f0-a09e-0ed4e5c87a06.png)

**Comment by devAbhishekYadav** [comment]
Resolved
