### ISSUE TITLE
Link name in Scuba diving masks & snorkels page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#20]
The link is showing only Scuba diving masks but in nav bar & collection page it is Scuba diving masks and snorkels.
![image](https://user-images.githubusercontent.com/97726944/171161214-fe1c14a7-1adf-4357-b6b8-3771b57e5d3e.png)

**Comment by devAbhishekYadav** [comment]
resolved
