### ISSUE TITLE
Cursor on hover

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#23]
The hand cursor should come while hovering on sortby filters & box
![image](https://user-images.githubusercontent.com/97726944/171161923-9c198a27-b9ee-4492-b946-32450c9ba99c.png)

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by Shoaibans** [comment]
@ui-chandrashekhar the hand cursor should come in the dropdown filters.
![image](https://user-images.githubusercontent.com/97726944/171351978-fafb4aeb-2c23-46fe-8980-84d6552e4f75.png)
