### ISSUE TITLE
Cursor on hover in product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#27]
While hovering to the dropdown box in product page, there should be hand cursor on hover.
![image](https://user-images.githubusercontent.com/97726944/171163224-7f43af42-d283-46bf-9950-601410d16dcb.png)

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by Shoaibans** [comment]
@ui-chandrashekhar the hand cursor should also come inside the drop down menus.
![image](https://user-images.githubusercontent.com/97726944/171351653-e64c13eb-9d32-4a5a-a166-f18a318e4f0e.png)
