### ISSUE TITLE
Name in link

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#3]
Steampunk & foldable sunglasses collection page link is showing mens foldable wrist hand sunglasses.
![image](https://user-images.githubusercontent.com/97726944/171150703-2eeb49e0-04c0-4254-8923-7d3129262b50.png)

**Comment by devAbhishekYadav** [comment]
resolved
![image](https://user-images.githubusercontent.com/89765850/171501265-ee2dca68-321d-4370-afa6-5f451535fd43.png)
