### ISSUE TITLE
Title centralization

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#30]
We can centralize the title in collections & product page.
![image](https://user-images.githubusercontent.com/97726944/171164281-036349cc-71be-4290-8636-2b7f24a59c88.png)
![image](https://user-images.githubusercontent.com/97726944/171164410-56a79a61-b33b-4010-a523-98ed7b33a2ad.png)
![image](https://user-images.githubusercontent.com/97726944/171165090-44f0adbf-f106-42ae-9444-73c584056d96.png)

**Comment by ui-chandrashekhar** [comment]
Resolved
