### ISSUE TITLE
Missing accordion

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#45]
The accordion is missing in footer.
![image](https://user-images.githubusercontent.com/97726944/171171493-1ef6e1a2-6875-4dfb-ba8a-e2c19ad63566.png)

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/171462469-ebb29d6c-b171-4bef-a432-ff8de26b1f12.png)
Accordion added on mobile view
