### ISSUE TITLE
Different product in different collection

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#5]
The cycling sunglasses collection page is having driving sunglass product.
https://k4yevf5hpl14tk20-52441481398.shopifypreview.com/collections/mens-cycling-sunglasses
Video: https://www.awesomescreenshot.com/video/9192091?key=eda57879f6467c07c5dffa6a56aa2f2e

**Comment by devAbhishekYadav** [comment]
@Shoaibans one driving sunglass product removed from cycling sunglasses category
