### ISSUE TITLE
Missing wishlist from header

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#51]
The wishlist is not coming in header.
![image](https://user-images.githubusercontent.com/97726944/171173109-1b96c03e-272a-4d37-8b34-da9859bc5b50.png)

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/171466337-b41d7470-978f-4d22-bc88-d42bb32809a2.png)
wishlist added at header
