### ISSUE TITLE
Product title in cart page iPad

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#52]
The title is coming very close to the quantity box in iPad.
![image](https://user-images.githubusercontent.com/97726944/171173642-405b1804-f8aa-439f-804e-c4832951620d.png)

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by Shoaibans** [comment]
@ui-chandrashekhar still coming same 
![image](https://user-images.githubusercontent.com/97726944/171366215-96e7bb00-aaba-42a7-ac53-a80208aaf700.png)
