### ISSUE TITLE
Cart & Wishlist icons alignment

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#54]
The cart & wishlist icons are not properly aligned with the background color, the icons should be in the center.
![image](https://user-images.githubusercontent.com/97726944/171364004-7e56e8c1-6f76-4bff-88d9-ed4608a8222e.png)

**Comment by ui-chandrashekhar** [comment]
@Shoaibans Resolved
