### ISSUE TITLE
Registration page input field text

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#59]
The registration page first name field is showing First Name inside the input field,
Either it should be in all the forms input fields or should not be there in any input field.
![image](https://user-images.githubusercontent.com/97726944/171376445-ce67f818-e314-49ed-aa11-ed3ec6679e3b.png)

**Comment by ui-chandrashekhar** [comment]
@Shoaibans Resolved
