### ISSUE TITLE
Banner linking below the featured collection

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Raymond-Store-Redesign--June-6#9]
The banner is not linked with any page.
![image](https://user-images.githubusercontent.com/97726944/171155506-a782a90f-0b53-4e8e-abed-330f869b6469.png)

**Comment by devAbhishekYadav** [comment]
resolved

**Comment by Shoaibans** [comment]
@devAbhishekYadav The banner is of Cycling sunglasses, but it is linked with Steampunk & Foldable sunglasses.
Pls check

**Comment by devAbhishekYadav** [comment]
@Shoaibans linking modified pls check
